before_install:
- sudo apt-get install lib32stdc++6
- sudo apt-get install lib32tinfo5

sudo: enabled

dist: trusty

language: generic

script:
# Install GMod
- cd ~
- wget http://media.steampowered.com/client/steamcmd_linux.tar.gz
- tar -xvzf steamcmd_linux.tar.gz
- ./steamcmd.sh +login anonymous +app_update 4020 validate +quit
# Make a symbolic link for the steam client
- mkdir -p .steam/sdk32
- ln -s linux32/steamclient.so ~/.steam/sdk32/steamclient.so
# Add to the server cfg
- echo "sv_hibernate_think 1" > /home/travis/Steam/steamapps/common/GarrysModDS/garrysmod/cfg/server.cfg
# Clone GUnit into our Project
- cd /home/travis/Steam/steamapps/common/GarrysModDS/garrysmod/addons/
- git clone https://github.com/Alig96/GUnit.git gunit
# Move the installed version of nZombies to the addons
- mv -v $TRAVIS_BUILD_DIR /home/travis/Steam/steamapps/common/GarrysModDS/garrysmod/addons
# Run the server & trigger the travis version of the test suite
- cd /home/travis/Steam/steamapps/common/GarrysModDS
- ./srcds_run -game garrysmod +gamemode nzombies +maxplayers 12 -noworkshop +map gm_flatgrass +hostname travis.nzombies5
# Check if we had any errors in the test suite
- if [ -e /home/travis/Steam/steamapps/common/GarrysModDS/garrysmod/data/gunit-build-status.txt ]; then exit 1; else exit 0; fi
